### ISSUE TITLE
synapse won't inject

### ISSUE THREAD

**Issue by greenmancode** [Idiomcode/JExecuter#2]
I try to run this:
`SynapseAPI.Inject()`

but it doesn't work. Give me my money back scammer!!!!!!!!!

**Comment by Idiomcode** [comment]
> I try to run this:
> `SynapseAPI.Inject()`
> 
> but it doesn't work. Give me my money back scammer!!!!!!!!!

AH IM SORRY LET ME ADD LUA SUPPORT DOH
